# -*- coding: utf-8 -*-
import card

CANCEL = '❌'
CHECK = '✅'
LEFT_ARROW = '⬅'
RIGHT_ARROW = '➡'
UNDER_CONSTRUCTION = '🚧'
BULLET = '🔹'
TIME_ICON = '⏱'
EXCLAMATION_ICON = '❗'
PLUS = '➕'
TROPHY = '🏆'
EYES = '👀'
PARTY = '🎉'
PROPHET = '🛐'
THUMB_UP = '👍'
THUMB_DOWN = '👎'
KEY = '🗝'
HAND = '✋'

INFO = "ℹ INFO"
BACK = "⬅ BACK"
REFRESH = "🔃 REFRESH"
DEMO_MODE = "🕹💻 DEMO MODE" # (vs computer)
MULTI_PLAYER_GAME = "🕹👥 MULTI-PLAYER"
NEW_GAME_ROOM = "🆕 NEW GAME ROOM"

YES_BUTTON = CHECK + ' YES'
NO_BUTTON = CANCEL + ' NO'

NO_PLAY_BUTTON = "🚫 NO PLAY"
SUBMIT_CARDS_BUTTON = "📤 SUBMIT"
EMPTY_SELECTION_BUTTON = "🗑 EMPTY"
CONFIRM_NO_PLAY_BUTTON = CHECK + " CONFIRM NO PLAY"
REMOVE_LAST_CARD = '🔙'

ASK_ME_TO_BE_A_PROPHET_ENABLED = "Ask me to be a prophet (✅ ENABLED)"
ASK_ME_TO_BE_A_PROPHET_DISABLED = "Ask me to be a prophet (❌ DISABLED)"

## CARDS SYMBOLS
CLUBS = '♣'
HEARTS = '♥️' #'♥'
SPADES = '♠'
DIAMONDS = '♦️'

SUITS_ICON = {
    card.CLUBS: CLUBS,
    card.HEARTS: HEARTS,
    card.SPADES: SPADES,
    card.DIAMONDS: DIAMONDS
}

ICON_SUITS = {i:s for s,i in SUITS_ICON.iteritems()}