# -*- coding: utf-8 -*-
import card

CANCEL = '❌'
CHECK = '✅'
LEFT_ARROW = '⬅'
RIGHT_ARROW = '➡'
UNDER_CONSTRUCTION = '🚧'
BULLET = '🔹'
TIME_ICON = '⏱'
EXCLAMATION_ICON = '❗'
PLUS = '➕'
TROPHY = '🏆'
EYES = '👀'

INFO = "ℹ INFO"
BACK = "⬅ BACK"
REFRESH = "🔃 REFRESH"
SINGLE_PLAYER_GAME = "🕹💻 SINGLE PLAYER" # (vs computer)
MULTI_PLAYER_GAME = "🕹👥 MULTI-PLAYER"
NEW_GAME_ROOM = "🆕 NEW GAME ROOM"

YES_BUTTON = CHECK + ' YES'
NO_BUTTON = CANCEL + ' NO'

NO_PLAY_BUTTON = "NO PLAY"
SUBMIT_CARDS_BUTTON = "PROPOSE CARD(S)"
EMPTY_SELECTION_BUTTON = "EMPTY SELECTION"
CONFIRM_NO_PLAY_BUTTON = "CONFIRM NO PLAY"

ASK_ME_TO_BE_A_PROPHET_ENABLED = "Ask me to be a prophet (✅ ENABLED)"
ASK_ME_TO_BE_A_PROPHET_DISABLED = "Ask me to be a prophet (❌ DISABLED)"

## CARDS SYMBOLS
CLUBS = '♣'
HEARTS = '♥️' #'♥'
SPADES = '♠'
DIAMONDS = '♦️'

SUITS_ICON = {
    card.CLUBS: CLUBS,
    card.HEARTS: HEARTS,
    card.SPADES: SPADES,
    card.DIAMONDS: DIAMONDS
}

ICON_SUITS = {i:s for s,i in SUITS_ICON.iteritems()}