# -*- coding: utf-8 -*-

from google.appengine.ext import ndb
import icons


INITIAL_DECKS = 3
CARDS_PER_PLAYER = 14
CARDS_PER_ROW = 6

CARDS_DISCOUNTED_ON_CORRECT_NO_PLAY = 4
CARDS_PENALTY_ON_INCORRECT_NO_PLAY = 5


GAME_EXPIRATION_SECONDS_IN_GAME = 1500
GAME_EXPIRATION_SECONDS_IN_WAITING_FOR_PLAYERS = 3000
MIN_WORDS_IN_SENTENCE = 5

GAME_ROOM_DUO = "2️⃣👤"
GAME_ROOM_TRIANGLE = "3️⃣👤"
GAME_ROOM_SQUARE = "4️⃣👤"
GAME_ROOM_PENTAGON = "5️⃣👤"
GAME_ROOM_EXAGON = "6️⃣👤"
PUBLIC_GAME_ROOM_NAMES = [GAME_ROOM_DUO, GAME_ROOM_TRIANGLE, GAME_ROOM_SQUARE, GAME_ROOM_PENTAGON, GAME_ROOM_EXAGON]
PUBLIC_GAME_ROOMS_INFO = {
    GAME_ROOM_DUO: {
        'PLAYERS': 2
    },
    GAME_ROOM_TRIANGLE: {
        'PLAYERS': 3
    },
    GAME_ROOM_SQUARE: {
        'PLAYERS': 4
    },
    GAME_ROOM_PENTAGON: {
        'PLAYERS': 5
    },
    GAME_ROOM_EXAGON: {
        'PLAYERS': 6
    }
}

